document_types:
  - Book
  - Book Chapter
  - Brochure
  - Document
  - Letter
  - Manuscript
  - Newsletter
  - OpenCourseWare
  - Pamphlet
  - Presentation
  - Press Release
  - Report
  - Software
  - White Paper
  - Video
