degrees:
  DMA: "Doctor of Musical Arts"
  PhD: "Doctor of Philosophy"
  MA: "Master of Arts"
  MFA: "Master of Fine Arts"
  MMS: "Master of Medieval Studies"
  MS: "Master of Science"
  MSAE: "Master of Science in Aerospace Engineering"
  MSBioE: "Master of Science in Bioengineering"
  MSChE: "Master of Science in Chemical Engineering"
  MSCE: "Master of Science in Civil Engineering"
  MSCSE: "Master of Science in Computer Science and Engineering"
  MSES: "Master of Science in Earth Sciences"
  MSEE: "Master of Science in Electrical Engineering"
  MSEnvE: "Master of Science in Environmental Engineering"
  MSGS: "Master of Science in Geological Sciences"
  MSIM: "Master of Science in Interdisciplinary Mathematics"
  MSME: "Master of Science in Mechanical Engineering"
  MADU: "Master of Architectural Design and Urbanism" 
  MArch: "Master of Architecture" 
  MSAM: "Master of Science in Applied Mathematics" 
  MSGS: "Master of Science in Geological Sciences"
