#
# FYI: This file is replaced by a copy for deploys
# to ci, pre_production, and production.
#

# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora.
<%
  port = ENV["SOLR_PORT"] || "8983"
  host = ENV["SOLR_HOST"] || "127.0.0.1"
%>

development:
  url: <%= "http://#{host}:#{port}/solr/development" %>
test: &TEST
  url: <%= "http://#{host}:#{port}/solr/test" %>
cucumber:
  <<: *TEST
ci:
  <<: *TEST
production:
  url: http://your.production.server:8080/bl_solr/core0
