# Work types must be whitelisted in order to be available as options for self
# deposit. Options are "all", "nobody", or one or more group PIDs.
Article:
  open: all
Dataset:
  open: all
Document:
  open: all
FindingAid:
  open: all
Image:
  open: all
SeniorThesis:
  open: all
Etd:
  open: all
Patent:
  open: all
