# Work types must be whitelisted in order to be available as options for self
# deposit. Options are "all", "nobody", or one or more group PIDs.
Article:
  open: all
Audio:
  open: all
CatholicDocument:
  open: all
Dataset:
  open: all
Document:
  open: all
Etd:
  open: nobody
FindingAid:
  open: all
Image:
  open: all
OsfArchive:
  open: nobody
Patent:
  open: all
SeniorThesis:
  open: all
Video:
  open: all
